phrase:
  project_id: 30dcea6240582b0c565cf0ed958f779f
  pull:
    targets:
    - file: ./qes/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
        tags: qes
    - file: ./fourthline/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
        tags: fourthline
        format_options:
          escape_linebreaks: true
    - file: ./bank/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
        tags: bank
    - file: ./startup/src/main/res/values-<locale_code>/strings.xml
      params:
        file_format: xml
        tags: startup