-keep class de.solarisbank.sdk.data.dto.** { *; }
-keep class * extends de.solarisbank.sdk.module.abstraction.IdenthubModule
-keepnames class * extends de.solarisbank.sdk.module.abstraction.IdenthubModule
-keepattributes *Annotation*
-keepattributes Signature